// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8IifNrD1ZDoxKFoDrzR9vlm3NUwUENHs',
    appId: '1:863499364117:web:6c9f3b09997c762125ab1c',
    messagingSenderId: '863499364117',
    projectId: 'talent-flow-1a793',
    authDomain: 'talent-flow-1a793.firebaseapp.com',
    storageBucket: 'talent-flow-1a793.firebasestorage.app',
    measurementId: 'G-29JF5G23CY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIEtvgw41mm0Qq_43HOKBj5Ud_u1BmBRU',
    appId: '1:863499364117:android:d2245cd4f79d96d725ab1c',
    messagingSenderId: '863499364117',
    projectId: 'talent-flow-1a793',
    storageBucket: 'talent-flow-1a793.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL_Dmf3ba_wu_w45VKDAnqjpNPlUFKWls',
    appId: '1:863499364117:ios:58b25af30802a06025ab1c',
    messagingSenderId: '863499364117',
    projectId: 'talent-flow-1a793',
    storageBucket: 'talent-flow-1a793.firebasestorage.app',
    iosBundleId: 'com.example.talentFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL_Dmf3ba_wu_w45VKDAnqjpNPlUFKWls',
    appId: '1:863499364117:ios:58b25af30802a06025ab1c',
    messagingSenderId: '863499364117',
    projectId: 'talent-flow-1a793',
    storageBucket: 'talent-flow-1a793.firebasestorage.app',
    iosBundleId: 'com.example.talentFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8IifNrD1ZDoxKFoDrzR9vlm3NUwUENHs',
    appId: '1:863499364117:web:b6751159aa1ff2a525ab1c',
    messagingSenderId: '863499364117',
    projectId: 'talent-flow-1a793',
    authDomain: 'talent-flow-1a793.firebaseapp.com',
    storageBucket: 'talent-flow-1a793.firebasestorage.app',
    measurementId: 'G-QMSB0K9BB3',
  );
}
